### ISSUE TITLE
No Description

### ISSUE THREAD

**Issue by refreshlearn** [max2dn/PointCloudBuilder#1]
Hi Can I get the details about the project.

Basically I am looking to create a pcd format file & convert it to obj in tango.
This project looks similar. Descritpiton & details of the project would be helpful

**Comment by max2dn** [comment]
Hi, the part of the project where we converted the pcd to obj was done on a server using Point Cloud Library. The purpose of this app was to collect the points to send to the server. The server would then send back the pcd file for one side. Once all sides had been collected, we would send it back to the server to be combined into a 3d render obj file and sent back.

**Comment by jcallin** [comment]
Hi @refreshlearn,

If you are interested in the code which does this conversion, it can be found in my repository in the file
https://github.com/jcallin/Senior-Design-2017-Backend/blob/master/web_server/greedy_projection/greedy_projection.cpp
in the function ProcessCloud()
I have knowledge about building PCL on Osx and Ubuntu 14.04 if you need assistance as well.

**Comment by refreshlearn** [comment]
Hi,

I am basically trying to

export a point cloud in obj format.

Load an obj format file in point cloud

Compare two point cloud

Could you please help me in this?

Regards,
Refresh Learn
